version: '3.8'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: news-app
        restart: always
        working_dir: /var/www
        volumes:
            - './:/var/www'
        networks:
            - laravel
    nginx:
        image: 'nginx:1.19-alpine'
        container_name: news-nginx
        restart: always
        ports:
            - '80:80'
        volumes:
            - './nginx:/etc/nginx/conf.d'
            - './:/var/www'
        networks:
            - laravel
    db:
        image: postgres:13
        container_name: postgres-db
        restart: always
        ports:
            -  "5432:5432"
        environment:
            POSTGRES_HOST: postgres-db
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
           - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: alishertaubaldy01@gmail.com
            PGADMIN_DEFAULT_PASSWORD: secret
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - db
        networks:
            - laravel
    redis-stack:
        image: redis/redis-stack  # Use the latest Redis Stack image
        container_name: news-redis-stack
        restart: always
        ports:
            - '6379:6379'  # Map Redis port to host port 6379
            - '8001:8001'
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - redis-data:/data
        networks:
            - laravel
volumes:
    db_data: { }
    pgadmin-data: { }
    redis-data: { }
networks:
    laravel: { }
